### ISSUE TITLE
Sync functionality on Indonesian App

### ISSUE THREAD

**Issue by mib-iqbal** [OpenSRP/opensrp-client-sid#12]
using cloudant sync

- [x] pull & push EC data to server (24 Nov)

#1 #4 #5 #6

**Comment by ainulhamdani** [comment]
Pull 
- [https://github.com/OpenSRP/opensrp-client-sid/commit/1e9aaca165d293c42567f39e986210f1a5889f95](url)


Push
- [https://github.com/OpenSRP/opensrp-client-sid/commit/bb64d070efbebab36f720fc9633e32a690e158ea](url)

**Comment by mib-iqbal** [comment]
Done, any additional sync feature will be worked on each module or new issue
