### ISSUE TITLE
Migrate Indonesia Vaccination app with the opensrp client core as dependencies

### ISSUE THREAD

**Issue by mib-iqbal** [OpenSRP/opensrp-client-sid#5]
#1 

- [x] setting gradle and dependencies

- [x] create login activity

- [x] create application class

- [x] Home Activity

- [x] Navigation Bar

- [x] Child Register and Activity

- [x] Mother Vaccin Register and Activity 

- [x] Add form

- [x] Data sync Functionality (EC)

- [x] Reporting 

- [x] Basic Feature (Shorting, Searching)

- [x] Detail Activity for Each Register 

- [x] Enketo form

- [x] Edit form

Due : 8 Dec 17

**Comment by baksosapi** [comment]
Closed  with #1
