### ISSUE TITLE
Migrate Indonesia Nutritionist app with the opensrp client core as dependencies

### ISSUE THREAD

**Issue by mib-iqbal** [OpenSRP/opensrp-client-sid#6]
To make sure consistency in coding style between opensrp client, All the indonesian app need to be migrated to replicate path app coding style. #1 

- [x] setting gradle and dependencies

- [x] create login activity

- [x] create application class

- [x] Nutritionist Repository

- [x] Home Activity

- [x] Navigation Bar

- [x] Child Register and Activity 

- [x] Growth Chart Activity 

- [x] Z-Score functionality 

- [x] Add form

- [x] Data sync Functionality (EC)

- [ ] Reporting 

- [x] Basic Feature (Shorting, Searching)

- [x] Detail Activity for Each Register 

- [x] Enketo Form

- [x] Edit Form

Due : 8 Dec 17

**Comment by baksosapi** [comment]
Closed with #1
